### ISSUE TITLE
Feature request - Auto-delete after reading message

### ISSUE THREAD

**Issue by agilob** [SilenceIM/Silence#448]
There are some kinds of text messages that should not be stored on phone, that expose information about owner, example, 2FA using text messages from Facebook, Github, Google or bank statements from your bank, bills from internet/water/power provides. Silence would offer a feature where text messages from a marked contact like Google would be deleted after closing window with the message.

1. Mark Google or GitHub contact as "Delete messages on exit"
2. Receive message from GitHub with code
3. Close text message window or preview
4. Message is automatically deleted

**Comment by pR0Ps** [comment]
One of the main goals of Silence is to keep things simple. In line with that goal, you should just manually delete the messages/conversations you're worried about.

The process for deleting a conversation (long press, trash icon, confirm) is simple enough that it doesn't need to be automated.

That being said, expanding the notification actions to include a "delete" action would make getting rid of 2FA codes and other transactional (read, action, delete) messages easier since you would be able to do it straight from the notification.
