### ISSUE TITLE
Is there a way for my contact to use Silence but keep Android integrated SMS app as default ? 

### ISSUE THREAD

**Issue by benoitne** [SilenceIM/Silence#464]
Hi, 
Everything in the title :)
I realized when I made some test with a friend that key exchange is ok but when I send him an encrypted message from Silence, then the message came into his default Android message app (he doesn't want to use Silence as the default SMS app).

Is there a way to detect that the message is encrypted and then redirect it to Silence app ?

**Comment by Tonat** [comment]
Afaik, Silence should automatically detect encrypted messenges even when not set as default sms app. Have you restricted any permissions? Details on OS, App Version ...

**Comment by pR0Ps** [comment]
Unfortunately due to the way Android does SMS intents (in KitKat+), Silence can't prevent the default SMS app from seeing the encrypted messages.

The default SMS app will always get the SMS. Non-default SMS apps can listen for the intent as well (this is what Silence does for encrypted messages when it isn't the default SMS app), but can't prevent other apps from seeing it.

The only way to stop another app from seeing the messages is to set Silence as the default SMS app.
