### ISSUE TITLE
Does it do any connections to OpenWhisperSystems?

### ISSUE THREAD

**Issue by rugk** [SilenceIM/Silence#473]
I'd like to know whether this app works fully decentralized. Therefore here a few questions:
1. How does Silence know whether the receiver supports Silence when I the sender sends a message? How does it get the public key and similar stuff?
2. In general does it connect to OpenWhisperSystems servers or other web servers at all?
3. If yes, is the phone number uploaded?

**Comment by pR0Ps** [comment]
1. Silence adds some extra whitespace the end of every unencrypted SMS message it send. When receiving messages, if that whitespace is present (meaning the message was most likely sent by a Silence client), it offers to encrypt the conversation. The clients then perform the key exchange over SMS.
2. No web services at all. The only reason it requires internet access is to retrieve MMS messages.

**Comment by rugk** [comment]
Thanks you for your answer. (Maybe put that info into the FAQ - at least I think that's quite good/important to know)

> The only reason it requires internet access is to retrieve MMS messages.

I'm not so deep involved into MMS, but are MMS messages really send over the (mobile) network?

**Comment by pR0Ps** [comment]
I'm not an expert either, but the way I understand it is that MMS messages are typically downloaded over the mobile connection, even if WiFi is enabled. This means you don't leave your providers network to retrieve the MMS messages.

However, since there's no distinction between mobile data and WiFi to Android's permission system, you need the internet permission, even though you only contact your provider, and not the "internet".
