### ISSUE TITLE
Sharing and Backup/Restore the Keystore

### ISSUE THREAD

**Issue by ThePreviousOne** [SilenceIM/Silence#475]
I would like to start work on an encrypted SMS patch for [ShellMS](https://github.com/try2codesecure/ShellMS) so it got me thinking.

//Backup
Is Silence compatible with Signal or other Signal forks? If so I'd like to be able to switch between them without having to re-authenticate with all my contacts or even If I reinstall the app or get a new phone.

//Sharing
The only case I can imagine for this to be useful is my own

**Comment by pR0Ps** [comment]
The encrypted backup is only compatible with Silence because it's basically a dump of it's private data folder. You can use this backup to switch phones or reinstall Silence.

The plaintext backup is in XML and compatible with the [SMS Backup & Restore](https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore) app. It's also pretty easy to parse though with an XML parser. However, the plaintext backup only contains SMS messages. No MMS, contact, or session data.

There is no ability for outside apps to access Silence's data. Since all the session information is in this data store, providing access to it would be unwise from a security standpoint.
