### ISSUE TITLE
Encrypted messages lost

### ISSUE THREAD

**Issue by js745oun** [SilenceIM/Silence#539]
### Encrypted messages lost

Since I encountered many lost messages since I started using Silence and nothing changed over various versions, I'm now writing this issue.

The messages seem to get lost occasionally on encrypted SMS. The option for the 'delivery report' is enabled. Both check marks are shown next to the lock symbol for every send SMS.
On most cases my chat partners do not receive the messages, sometimes I don't receive their messages.

The Android versions and mobiles phones differ from stock Android 5.x to 7.x, so I doubt it has anything to do with Android but rather with the App itself ...

Anyone else having this issue?

**Comment by js745oun** [comment]
Here is the debug log https://gist.github.com/a9ccbeabac249b25ebeea7e8db91146a

**Comment by Kristaba** [comment]
Not a very useful message, as I have no log right now, but me and several friend have similar issues.
As you said, the lost message still show the delivery report, so I imagine the issue is in Silence, when processing a received message.

Almost all my friend using Silence have it sometimes, from the time we began to use it (~1 year ago).
Unfortunately, it seems especially hard to track...
- it seems to be highly random (I was unable to notice any _pattern_, for instance resending the same message usually works)
- it occurs rarely, at least for me (maybe 1% of the time or so)
- as the receiver just don't see anything, it often takes several days for me to be aware that the bug occurs on my phone

I will try to reproduce it by sending dozens/hundreds of messages if I have some time, to be able to see if something is visible in the logs.
However, I don't remember to be aware of a lost message for around 1 month, so maybe the problem was fixed recently, but for all the mentioned reasons it's difficult to be sure...

**Comment by goncalor** [comment]
I recently started using the beta version of the app (I previously used the stable version). One of my contacts uses the stable version. Since then, some encrypted SMS are not delivered (even though the check mark indicating delivery appears).

I managed to find some pattern for the unreceived messages:

- Messages with ASCII characters only (7-bit characters) are received only if they have less than 64 characters
  - for example this message is received (63 chars)
     `AaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaa`
  - while this one is not (64)
     `AaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaa`
- Messages with non-ASCII characters support even less characters
  - this message is received (62) (note the `ã` at the end)
     `AaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaã`
  - while this one is not (63)
     `AaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaaaAaaaaaã`
  - and neither is this (40)
     `ÃãããããããÃãããããããÃãããããããÃãããããããÃããããããã`

I can't find the exact pattern for non-ASCII characters right now. 

These results are consistent across my experiments. Hope they help in finding the problem.

**Comment by mohicanb** [comment]
Hello, I am experiencing the same problem. Some SMS are lost both incoming and outgoing.
But this **occurred with unencrypted messages as well.** (i.e. with people not running Silence).

Using Silence 0.15.7 from F-Droid (same problem on two different phones, running Android 6).
