### ISSUE TITLE
Is Silence still in active development?

### ISSUE THREAD

**Issue by johanw666** [SilenceIM/Silence#610]
It has been nearly 4 months since the last commit, despite there being serious issues with the unstable versions and lively discussions about the addition of a xmpp message protocol some time ago. Are the maintainers still working on Silence in the background?

**Comment by BLeQuerrec** [comment]
Yes is it. ;-)
I am quite busy since may and until the end of the month. But Silence is still in active development.
Good news: code has been audited during the summer. Results will be published later as I can't disclose anything right now. Additionally, I'll start to sync Silence's codebase with Signal to backport new features and bug fixes as soon as possible.
Finally, there's a [warrant canary](https://silence.im/#warrant-canary) to ensure project is still in development and safe.

**Comment by johanw666** [comment]
Good to hear that. I'm curious to the new developments.

**Comment by FilLupin** [comment]
Thank you for the news, and for the time you spent on this audit.

**Comment by 1xPdd** [comment]
Yes, this is great news. Really happy to hear development progress is being made.

@BLeQuerrec Is there a PayPal account or it Bitcoin the only way to donate?

**Comment by BLeQuerrec** [comment]
Bitcoin is the only way to donate as it offers transparency on the way
we use funds.

**Comment by 1xPdd** [comment]
@BLeQuerrec, thanks for the clarification. Glad to hear about the progress and eagerly looking forward to seeing all the new developments.
