### ISSUE TITLE
Gradle version upgrade

### ISSUE THREAD

**Issue by buzuck** [SilenceIM/Silence#626]
When upgrading the project to the latest version of Gradle (3.0.0 -- or is it 4.1 ?), the following error occurs :
``` A problem occurred configuring root project 'Silence'.
> Could not resolve all dependencies for configuration ':compile'.
   > A problem occurred configuring project ':org.whispersystems.libsignal'.
      > Cannot set the value of read-only property 'outputFile' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.
```

The incriminated code :

```
  libraryVariants.all { variant ->
         variant.outputs.each { output ->
             def outputFile = output.outputFile
             if (outputFile != null && outputFile.name.endsWith('.aar')) {
                 def fileName = "${archivesBaseName}-${version}.aar"
                 output.outputFile = new File(outputFile.parent, fileName)
             }
         }
     }
```

I stumbled upon this on Stackoverflow, but as I'm new on Android development, I couldn't figure out what is wrong
https://stackoverflow.com/questions/24728591/how-to-set-name-of-aar-output-from-gradle

**Comment by johanw666** [comment]
Gradle plugin updates often lead to issues. If you load the project in Android Studio and it asks to upgrade the Gradle plugin, just say "no, don't remind me again for this project".

Having said that, building Silence from Android Studio 3 requires a lttle upgrade from used Gradle wrapper. In the file gradle-wrapper.properties it works to change the line
```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-bin.zip
```
to ```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip
```
And either find out the new distributionSha256Sum and replace that too, or remove the line like I did for testing (otherwise Android Studio crashes on my system).

**Comment by buzuck** [comment]
Thanks for the tip about the `distributionUrl`. However, as I understand it, it's only a workaround as migrating to gradle 4 may be necessary at some point.

Maybe when that version's api will be able to replace the one of the v3. If I'm correct, the v4 still lacks functionalities that might be needed here.

**Comment by johanw666** [comment]
Odd. The changes I mentioned above are required when I want to build 0.15.8 on Android Studio 3 for Linux, but they give a build error building 0.15.9 on Android Studio 3 and 3.1 for Windows. For Windows it works to let gradle-wrapper.properties untouched. I'm a bit confused now. I'll test 0.15.9 on Linux just to be sure.
