### ISSUE TITLE
Release update to at least have the latest translations + eventually train a new maintainer

### ISSUE THREAD

**Issue by tuxayo** [SilenceIM/Silence#753]
Even if it will only be publishable on F-Droid due to #717

@BLeQuerrec Is there enough available maintenance work-time for this? That "empty" release could be a good opportunity to guide someone willing the help with the maintenance

**Comment by 1anomaly1** [comment]
Sounds wonderful, this app is really needed as my portfolio of secure apps is dwindling. Don't like to depend on one single app because of this kind of desertion. However, I'm certainly thankful for the work done thus far. I will have to say though, I'm hesitant to believe anyone can be trained for the same apparent time constraints that still exist for the trainer. In my mind, these kinds of apps are more important than the developer's current interests, whatever they may be. Private, secure comms are of critical importance at all times, and the numbers of worthless masses of idiots are stacked against us, let alone corrupt government. OUR OWN FAMILIES ARE UNFORTUNATELY OUR NUMBER ONE ENEMIES, OTHER THAN THE DEVIL HIMSELF.

**Comment by 1anomaly1** [comment]
NSA IS A CRIME.

**Comment by PeekFreansCDN** [comment]
I'd love to help maintain this if anyone is willing to guide me loosely. Whatever it takes to keep this app relevant and not deprecated.

**Comment by 1anomaly1** [comment]
I'LL NEVER PUT MY CODE ON THIS BILL GATES SHITHOLE. ONLY FAGGOTS SELL TO BILL GATES. MICROSOFT SHOULD BE HACKED TILL INOPERABLE .....OH YEA, IT ALREADY IS. LOL, LIKE WORMHOLES IN THE BRAIN.

**Comment by BLeQuerrec** [comment]
Sorry for the absence. Different things appended.

All I ask is to wait until the end of the week: next update will unblock a *lot* of things. I'll then explained what append and what's next. No, the project is not dead (it's far from being dead).

**Comment by rugk** [comment]
I am eager to see the new changes. 😄

**Comment by BLeQuerrec** [comment]
#717 will be fixed and MMS support will be improved.

**Comment by 1anomaly1** [comment]
RESULTS. NOT EXCUSES.

**Comment by 1anomaly1** [comment]
ZRTP CALLS.

**Comment by thiswillbeyourgithub** [comment]
@1anomaly1 you're not helping at all. You're just being aggresive and spamming everyone's mailbox, including the devs.
Either help with code, money or bug reports but don't do that please.

**Comment by 1anomaly1** [comment]
YOU ARE THE BUG REPORT. DON'T ACT LIKE YOUR IN CHARGE, BECAUSE YOUR NOT HERE TO HELP, YOUR HERE TO SUBVERT THE CAUSE, AND GET RID OF SILENCE FANS.

**Comment by 1anomaly1** [comment]
"Thiswill" is an NSA faggot.

**Comment by 1anomaly1** [comment]
DON'T TRUST "Thiswillbeyourgithub". This dude wants to act like he's in charge of development, and run off all the privacy fans because he sucks conventional dick at CIA.

**Comment by 1anomaly1** [comment]
PLAIN AND SIMPLE. I SMELLED YOUR GREASY PORK SLUDGE QUITE AWHILE AGO. YOUR NOT FOOLING ME DUDE. NOBODY ELSE ACTS LIKE "Thiswillbeyourgithub" on this forum for a reason. Cause your a filthy NSA PIG.

**Comment by 1anomaly1** [comment]
DEFINITELY MILITARY. A MILITARY PIG NO DOUBT.
